server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

bookmarks:
  folder: ui

  # The RSA key pair encoded in Base64
activeviam:
  jwt:
    key:
      public: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkirRjoq1RSB+Z4TZ7ZK+D4If2qYWdUX6wt3K1AQYk2kfeyv2v\
        +yros0NlAJRirgV9H4v3HiYFL5AK9YGI9Lq7mvZ4CpJX/RQKqClLHFwcKx+CWNcqhka7qFm4u97ZDSP5mEn89\
        jXFzWtc5mnvhkVW8mWdF5PQMT4rXkZSw0051tomTeGGP0tYrGwSgpQYCkQJC8ff7NLjHI201O61O96hLyM5X2GNaNQqNTw\
        24aUelNmdQhiRnODmZz+lDizALHdyJMXv9hfRZHOXja31TOpXELCmDU1omFqwTRPdYpCYdQ3+Ycr8dt2VUxak+kEWoPUsn\
        B3BHWJ4M9hcP0R96ZalwIDAQAB"
      private: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSKtGOirVFIH5nhNntkr4Pgh/aphZ1RfrC3crUBBiTaR97K\
        /a/7KuizQ2UAlGKuBX0fi/ceJgUvkAr1gYj0urua9ngKklf9FAqoKUscXBwrH4JY1yqGRruoWbi73tkNI/mYSfz2NcXNa1zmae+\
        GRVbyZZ0Xk9AxPiteRlLDTTnW2iZN4YY/S1isbBKClBgKRAkLx9/s0uMcjbTU7rU73qEvIzlfYY1o1Co1PDbhpR6U2Z1CGJGc4O\
        ZnP6UOLMAsd3Ikxe/2F9Fkc5eNrfVM6lcQsKYNTWiYWrBNE91ikJh1Df5hyvx23ZVTFqT6QRag9SycHcEdYngz2Fw/RH3plqXAg\
        MBAAECggEAHgiCSoGhwXRtxKN9i90tBE6+cNTTpIEeh0+/T1UQH6nn+A0OhF0C3062zYS0cIZmrHgJKYn15b05vkg\
        Ztt6tuxOaDv9hWEABAOFFTx539g7bTt6FucWyzPmJBHQkrHBIaRPpe6dAetpiq3AVEXBh/Rwst/hw3GQcnLhXRB6QkkDcH7n3wfrX\
        JT9Y8Y6U4iwhdXLIhcI7i7lmBbVHnj1VKtvxtrtB1KU3BaFx4kZi5Z3RwC17YlEjJPLlwgAq5zUMJc5rN5lPEIciBETKhDd1yNHeV/\
        b8YpqpzCMZ/J2dT32vs0XhS59kX/wPmIoGR37hqod1q5zHI4lj4ZjYQBo1QQKBgQDU1y2rk8KBw/vPBAXOdc1bnuHCxJvf/DpVJGdf\
        JaIMUXX8gfDZ7yyjrJc5yKo3184/50rgLglzpZzs4yGWPkTXM8QJfxDZ8zjz/xvb9XI1ga9uQPsyLfye9Vhh4/0Ob8eBBJWLJiSynV\
        ieJsO0/5ZJEYpCSd7dnAL+o0vXV1shRwKBgQCvzou+13VuNpkElBXMiaZZRtP1pMviYcaeqwUy+QIop61Jp9sjltJQdmVXy/H5UniK\
        GDEaOVTHyU0WbWnBGeBvDHPIv8MFiK0jARmW2HS5itAHKO3Ptwab1fStgeTrm3SROJeocpP5h/XfjAbNEGIixqIks4vI0SoVGz4j6M\
        EkMQKBgDpQim7MGSq8q61YiM68b/t+WJSokZyY2tKhGsFy6ic92nnIkFjlsvFVREnMtPZ/5j6T/GvXsTdCVPCCep1TikD8KeYALnnI\
        rf4ME3H8mcIXOh2XKDvjZaeXyRNpB9iAv8SVoPNzC/L0MWeDb3OT43U5nQv0eV92c0uZKhpiENHZAoGBAJ1+5LRP4vScVtLCMxEsk2\
        jRSdt7CefBfiTwwtSaPPPc2yHsDSZB3CGXH0za+OhJmJDmAT8j8y6TyMp5tE74dpYlSqiiGf0gJzL/rkPzoAYEND7lzL3TkkkTEIJL\
        pp/ngTMDxuFx29ykj4D3ubQFpFTRK7rDWkvKDfAgmreisTxRAoGAam5RZq1F2cVW/VETePpD9cvojReFUiqaxwvVpqNtykC7jAOW96\
        lULiNZ73+TSdoT8yD6mH2hVArkajsnv1PNw0cR2V2aLY1Cg030jyTtmdOky/ZBhMiT/bH7H1M/BNjsC23rcOtdwFRlApUlOkGMecZN\
        8IzqaYV0zuL+cQt2Iwo="
    # The time of validity of a token in seconds
    expiration: PT24H

# The path of the folder containing statistic files in .json or .json.sz (Snappy-compressed) formats
# This path is relative to the execution directory of the Application
statistic:
  folder: input_statistics

content-service:
  mode: "in-memory" # "in-memory" or "db"
  db:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: false
      #The following line should be removed once the table is created
      hbm2ddl.auto: update
      # Connection Provider
      connection:
        provider_class: org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl

    # Tomcat connection pool settings. List of properties can be found in org.apache.tomcat.jdbc.pool.DataSourceFactory
    # or https://tomcat.apache.org/tomcat-8.0-doc/jdbc-pool.html
    url: jdbc:h2:file:./content_service;DB_CLOSE_DELAY=-1
    defaultAutoCommit: false
    driverClassName: org.h2.Driver
    jdbcInterceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState
