version: 2.1

parameters:
  head_ref:
    type: string
    default: NONE
  base_ref:
    type: string
    default: NONE
  run_compatibility:
    type: boolean
    default: false
executors:
  jdk11-docker:
    docker:
      - image: circleci/openjdk:11-jdk-node
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
  vm:
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    machine:
      image: ubuntu-2004:202201-02

jobs:
  build_and_test:
    executor: vm
    resource_class: large
    working_directory: ~/mac
    steps:
      - checkout
      - restore_cache:
          keys:
            - mac-java-{{ .Branch }}-{{ checksum "pom.xml" }}
            - mac-java-{{ .Branch }}-
            - mac-java-
      - run:
          name: "Build and test"
          command: |
            sudo sysctl -w vm.overcommit_memory=1
            mkdir -p "$HOME/.m2/repository"
            docker run --rm --privileged \
              -e ACTIVEPIVOT_LICENSE -e ARTIFACTORY_USER -e ARTIFACTORY_PASSWORD \
              -v "$HOME/.m2/repository:/tmp/repository" \
              -v "$PWD:/home/circleci/mac" \
              -w /home/circleci/mac -u root \
              circleci/openjdk:11-jdk-node-browsers \
              mvn package --settings .circleci/circleci-settings.xml -Dmaven.repo.local=/tmp/repository
      - save_cache:
          paths: [ ~/.m2/repository ]
          key: mac-java-{{ .Branch }}-{{ checksum "pom.xml" }}

  launch_compatibility_checks:
    executor: vm
    resource_class: medium
    steps:
      - unless:
          condition: <<pipeline.parameters.run_compatibility>>
          steps:
             - run:
                name: Fail if no compatibility enabled
                command: exit 1
      - when:
          condition: <<pipeline.parameters.run_compatibility>>
          steps:
            - checkout
            - run:
                name: Compatibility enabled, fetch matching releases using artifacts.activeviam.com
                command: bash ./scripts/get_compatible_ap_releases.sh
  compatibility_check:
    executor: vm
    resource_class: large
    working_directory: ~/mac
    parameters:
      ap-version:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - mac-java-{{ .Branch }}-{{ checksum "pom.xml" }}
            - mac-java-{{ .Branch }}-
            - mac-java-
            - mac-export-<< parameters.ap-version >>-{{ checksum "pom.xml" }}
      - run:
          name: "Run matrix checks"
          command: |
            sudo sysctl -w vm.overcommit_memory=1 && \
            ARTIFACT_ARG=${ARTIFACTS_USER}:${ARTIFACTS_PASSWORD} && \
            echo $ARTIFACT_ARG && \
            # using cached exports if available
            if [[ ! -d target/exported_statistics || -z $(ls -A target/exported_statistics) ]]; then
              bash ./scripts/sandbox_export_generator.sh << parameters.ap-version >> ARTIFACT_ARG
            fi
            bash ./scripts/mac_export_load.sh $(cat ./logs/jmxterm.log | tail -1)
      - store_artifacts:
          path: ./logs
      - save_cache:
          paths: [ target/exported_statistics ]
          key: mac-export-<< parameters.ap-version >>-{{ checksum "pom.xml" }}
workflows:
  version: 2
  check:
    jobs:
      - build_and_test:
          context: rnd-server
      - launch_compatibility_checks:
          context: rnd-server
          requires:
            - build_and_test
      - compatibility_check:
          matrix:
            parameters:
              ap-version: [
                  "5.8.0",
                  "5.8.1",
                  "5.8.2",
                  "5.8.3",
                  "5.8.4",
                  "5.8.5",
                  "5.8.6",
                  "5.8.7",
                  "5.8.8",
                  "5.8.9",
                  "5.8.10",
                  "5.8.11",
                  "5.8.12",
                  "5.8.13",
                  "5.8.14",
                  "5.8.15",
                  "5.8.16",
                  "5.8.17",
                  "5.8.18",
                  "5.8.19",
                  "5.8.20",
                  "5.8.21",
                  "5.8.22",
                  "5.8.23",
                  "5.8.24",
                  "5.9.0",
                  "5.9.1",
                  "5.9.2",
                  "5.9.3",
                  "5.9.4",
                  "5.9.5",
                  "5.9.6",
                  "5.9.7",
                  "5.9.8",
                  "5.9.9",
                  "5.9.10",
                  "5.9.11",
                  "5.9.12",
                  "5.9.13",
                  "5.10.0",
                  "5.10.1",
                  "5.10.2",
                  "5.10.3",
                  "5.10.4",
                  "5.10.5",
                  "5.10.6",
                  "5.10.7",
                  "5.10.8",
                  "5.10.9",
                  "5.10.10",
                  "5.10.11",
                  "5.10.12",
                  "5.10.13",
                  "5.11.0",
                  "5.11.1",
                  "5.11.2",
                  "5.11.3",
                  "5.11.4",
                  "5.11.5",
                  "6.0.0",
                  "6.0.1",
                  "6.0.2"
              ]
          context: rnd-server
          requires:
            - launch_compatibility_checks
