name: Autosquash
on:
  check_run:
    types:
      - completed
  pull_request:
    types:
      - closed
      - labeled
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  autosquash:
    name: Autosquash
    runs-on: ubuntu-18.04
    steps:
      - name: Autosquash
        uses: tibdex/autosquash@v2
        with:
          # We can't use the built-in secrets.GITHUB_TOKEN yet because of this limitation:
          # https://github.community/t5/GitHub-Actions/Triggering-a-new-workflow-from-another-workflow/td-p/31676
          # In the meantime, use a personal access token with repo access.
          github_token: ${{ secrets.AUTOSQUASH_TOKEN }}
