name: Autosquash
on:
  check_run:
    types:
      - completed
  pull_request:
    types:
      - closed
      - labeled
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  autosquash:
    name: Autosquash
    runs-on: ubuntu-18.04
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.JMP_APP_ID }}
          private_key: ${{ secrets.JMP_PRIVATE_KEY }}
      - uses: tibdex/autosquash@v2
        with:
          # See https://github.com/tibdex/autosquash/blob/a0526e5a03e31c20e3d592d1130ad6297d9400e8/.github/workflows/autosquash.yml#L33-L37
          github_token: ${{ steps.generate_token.outputs.token }}
